# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5fa445e82bf260c3c538a1f73e5777b7d7b0d932ea55165827e87f04109e9327c6101b1ec7acde5ca485352bc38c820538ee0ffb777061a13fc26f89f10fec2

test:
  secret_key_base: d36e36fcf9c7c840cf08d9627b2c969b4ba0561f2f8b6b28047663a69458a9033e0c3ec64ef1c4c13d1ab93057b4436b4c0055e5359e3c567c10ae66f667f298

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
